// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OwTracker.Data;

#nullable disable

namespace OwTracker.Data.Migrations
{
    [DbContext(typeof(OwTrackerDbContext))]
    partial class OwTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("OwTracker.Core.Models.HeroPlaytime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeroName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("TimePlayed")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerRecordId");

                    b.ToTable("HeroPlaytimes");
                });

            modelBuilder.Entity("OwTracker.Core.Models.MatchRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnemyTeamScore")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("GameLength")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MapName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MatchDatetime")
                        .HasColumnType("TEXT");

                    b.Property<int>("MyTeamScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueueType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RankingMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScrapedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MapName", "MatchDatetime")
                        .IsUnique();

                    b.ToTable("MatchRecords");
                });

            modelBuilder.Entity("OwTracker.Core.Models.PendingHeroLabel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<float>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("ConfirmedHero")
                        .HasColumnType("TEXT");

                    b.Property<string>("CropPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PredictedHero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Reviewed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("PendingHeroLabels");
                });

            modelBuilder.Entity("OwTracker.Core.Models.PlayerRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Assists")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DamageDealt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DamageMitigated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Deaths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eliminations")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndingHero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HealingDone")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MatchRecordId");

                    b.ToTable("PlayerRecords");
                });

            modelBuilder.Entity("OwTracker.Core.Models.SessionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("ActiveDuration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SessionEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SessionStart")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TotalOpenDuration")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SessionRecords");
                });

            modelBuilder.Entity("OwTracker.Core.Models.HeroPlaytime", b =>
                {
                    b.HasOne("OwTracker.Core.Models.PlayerRecord", "Player")
                        .WithMany("HeroPlaytimes")
                        .HasForeignKey("PlayerRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("OwTracker.Core.Models.PlayerRecord", b =>
                {
                    b.HasOne("OwTracker.Core.Models.MatchRecord", "Match")
                        .WithMany("AllPlayers")
                        .HasForeignKey("MatchRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("OwTracker.Core.Models.MatchRecord", b =>
                {
                    b.Navigation("AllPlayers");
                });

            modelBuilder.Entity("OwTracker.Core.Models.PlayerRecord", b =>
                {
                    b.Navigation("HeroPlaytimes");
                });
#pragma warning restore 612, 618
        }
    }
}
